LOC 6 ;BEGIN AT LOCATION 6
Data 10 ;PUT 10 AT LOCATION 6
Data 3 ;PUT 3 AT LOCATION 7
Data End ;PUT 1024 AT LOCATION
IN 1,0 ;GET INPUT FROM CONSOLE KEYBOARD TO r=1
OUT 2,1 ;OUTPUT r=2 TO CONSOLE PRINTER
CHK 3,1 ;PUT CONSOLE PRINTER STATUS TO r=3
IN 2,0 ;GET INPUT FROM CONSOLE KEYBOARD TO r=2
OUT 3,1 ;OUTPUT r=3 TO CONSOLE PRINTER
CHK 0,1 ;PUT CONSOLE PRINTER STATUS TO r=4
LOC 1024
End: HLT ;STOP 